ERROR - 2024-04-12 00:13:25 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'test', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(420): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(603): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(41): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(420): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(603): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(41): CodeIgniter\Model->insert(Array)
#7 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#14 {main}
CRITICAL - 2024-04-12 00:13:25 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: POST, Route: auth/register]
in SYSTEMPATH\Database\BaseConnection.php on line 456.
 1 SYSTEMPATH\Database\BaseConnection.php(603): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 3 SYSTEMPATH\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(790): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Auth.php(41): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
ERROR - 2024-04-12 00:18:22 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'test', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(420): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(603): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(41): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(420): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(603): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(41): CodeIgniter\Model->insert(Array)
#7 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#14 {main}
CRITICAL - 2024-04-12 00:18:22 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: POST, Route: auth/register]
in SYSTEMPATH\Database\BaseConnection.php on line 456.
 1 SYSTEMPATH\Database\BaseConnection.php(603): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 3 SYSTEMPATH\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(790): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Auth.php(41): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
ERROR - 2024-04-12 00:19:37 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'test', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(420): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(603): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(41): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(420): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(603): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(41): CodeIgniter\Model->insert(Array)
#7 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#14 {main}
CRITICAL - 2024-04-12 00:19:37 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: POST, Route: auth/register]
in SYSTEMPATH\Database\BaseConnection.php on line 456.
 1 SYSTEMPATH\Database\BaseConnection.php(603): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 3 SYSTEMPATH\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(790): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Auth.php(41): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
ERROR - 2024-04-12 00:20:32 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'test', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(420): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(603): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(41): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(420): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(603): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(41): CodeIgniter\Model->insert(Array)
#7 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#14 {main}
CRITICAL - 2024-04-12 00:20:32 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: POST, Route: auth/register]
in SYSTEMPATH\Database\BaseConnection.php on line 456.
 1 SYSTEMPATH\Database\BaseConnection.php(603): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 3 SYSTEMPATH\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(790): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Auth.php(41): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
ERROR - 2024-04-12 00:20:52 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'test', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(420): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(603): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(41): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(420): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(603): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(41): CodeIgniter\Model->insert(Array)
#7 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#14 {main}
CRITICAL - 2024-04-12 00:20:52 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: POST, Route: auth/register]
in SYSTEMPATH\Database\BaseConnection.php on line 456.
 1 SYSTEMPATH\Database\BaseConnection.php(603): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 3 SYSTEMPATH\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(790): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Auth.php(41): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
ERROR - 2024-04-12 00:22:45 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'test', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(420): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(603): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(44): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(420): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(603): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(44): CodeIgniter\Model->insert(Array)
#7 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#14 {main}
CRITICAL - 2024-04-12 00:22:45 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: POST, Route: auth/register]
in SYSTEMPATH\Database\BaseConnection.php on line 456.
 1 SYSTEMPATH\Database\BaseConnection.php(603): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 3 SYSTEMPATH\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(790): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Auth.php(44): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
ERROR - 2024-04-12 00:23:25 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'test', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(420): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(603): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(44): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(420): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(603): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#6 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(44): CodeIgniter\Model->insert(Array)
#7 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#14 {main}
CRITICAL - 2024-04-12 00:23:25 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: POST, Route: auth/register]
in SYSTEMPATH\Database\BaseConnection.php on line 456.
 1 SYSTEMPATH\Database\BaseConnection.php(603): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 3 SYSTEMPATH\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(790): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Auth.php(44): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
ERROR - 2024-04-12 00:23:48 --> mysqli_sql_exception: Duplicate entry 'rafee1s32@gmail.com' for key 'email' in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(44): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}
CRITICAL - 2024-04-12 00:23:48 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'rafee1s32@gmail.com' for key 'email'
[Method: POST, Route: auth/register]
in SYSTEMPATH\Database\BaseConnection.php on line 675.
 1 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 2 SYSTEMPATH\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(790): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Auth.php(44): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
CRITICAL - 2024-04-12 00:23:48 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'rafee1s32@gmail.com' for key 'email'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`name`, `email`, `password`) VALUES (\'tausifrasfee123\', \'rafee1s32@gmail.com\', \'$2y$10$jicOrwwec51.uZJHsmKsneRQkIBmKekCZgrlB.qzF5I0uKdJolzJW\')')
 2 SYSTEMPATH\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`name`, `email`, `password`) VALUES (\'tausifrasfee123\', \'rafee1s32@gmail.com\', \'$2y$10$jicOrwwec51.uZJHsmKsneRQkIBmKekCZgrlB.qzF5I0uKdJolzJW\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 4 SYSTEMPATH\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(790): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Auth.php(44): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
CRITICAL - 2024-04-12 00:23:48 --> [Caused by] mysqli_sql_exception: Duplicate entry 'rafee1s32@gmail.com' for key 'email'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `user` (`name`, `email`, `password`) VALUES (\'tausifrasfee123\', \'rafee1s32@gmail.com\', \'$2y$10$jicOrwwec51.uZJHsmKsneRQkIBmKekCZgrlB.qzF5I0uKdJolzJW\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`name`, `email`, `password`) VALUES (\'tausifrasfee123\', \'rafee1s32@gmail.com\', \'$2y$10$jicOrwwec51.uZJHsmKsneRQkIBmKekCZgrlB.qzF5I0uKdJolzJW\')')
 3 SYSTEMPATH\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`name`, `email`, `password`) VALUES (\'tausifrasfee123\', \'rafee1s32@gmail.com\', \'$2y$10$jicOrwwec51.uZJHsmKsneRQkIBmKekCZgrlB.qzF5I0uKdJolzJW\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 5 SYSTEMPATH\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(790): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Auth.php(44): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
CRITICAL - 2024-04-12 00:24:38 --> Error: Class "Firebase\JWT\JWT" not found
[Method: POST, Route: auth/register]
in APPPATH\Controllers\Auth.php on line 63.
 1 APPPATH\Controllers\Auth.php(44): App\Controllers\Auth->generateJWT('rafee1w4s332@gmail.com')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
CRITICAL - 2024-04-12 00:27:23 --> Error: Class "Firebase\JWT\JWT" not found
[Method: POST, Route: auth/register]
in APPPATH\Controllers\Auth.php on line 69.
 1 APPPATH\Controllers\Auth.php(45): App\Controllers\Auth->generateJWT('rafee1w4s3332@gmail.com')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
ERROR - 2024-04-12 00:27:39 --> mysqli_sql_exception: Duplicate entry 'rafee1w4s3332@gmail.com' for key 'email' in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(42): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}
CRITICAL - 2024-04-12 00:27:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'rafee1w4s3332@gmail.com' for key 'email'
[Method: POST, Route: auth/register]
in SYSTEMPATH\Database\BaseConnection.php on line 675.
 1 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 2 SYSTEMPATH\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(790): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Auth.php(42): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
CRITICAL - 2024-04-12 00:27:39 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'rafee1w4s3332@gmail.com' for key 'email'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`name`, `email`, `password`) VALUES (\'tauwsifr3asfe3e1243\', \'rafee1w4s3332@gmail.com\', \'$2y$10$0/E8nUhPBi12WS4.bQQtUOV3lxCOM35GoDGdUuK.Qc/0pGaJQmDxC\')')
 2 SYSTEMPATH\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`name`, `email`, `password`) VALUES (\'tauwsifr3asfe3e1243\', \'rafee1w4s3332@gmail.com\', \'$2y$10$0/E8nUhPBi12WS4.bQQtUOV3lxCOM35GoDGdUuK.Qc/0pGaJQmDxC\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 4 SYSTEMPATH\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(790): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Auth.php(42): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
CRITICAL - 2024-04-12 00:27:39 --> [Caused by] mysqli_sql_exception: Duplicate entry 'rafee1w4s3332@gmail.com' for key 'email'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `user` (`name`, `email`, `password`) VALUES (\'tauwsifr3asfe3e1243\', \'rafee1w4s3332@gmail.com\', \'$2y$10$0/E8nUhPBi12WS4.bQQtUOV3lxCOM35GoDGdUuK.Qc/0pGaJQmDxC\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`name`, `email`, `password`) VALUES (\'tauwsifr3asfe3e1243\', \'rafee1w4s3332@gmail.com\', \'$2y$10$0/E8nUhPBi12WS4.bQQtUOV3lxCOM35GoDGdUuK.Qc/0pGaJQmDxC\')')
 3 SYSTEMPATH\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`name`, `email`, `password`) VALUES (\'tauwsifr3asfe3e1243\', \'rafee1w4s3332@gmail.com\', \'$2y$10$0/E8nUhPBi12WS4.bQQtUOV3lxCOM35GoDGdUuK.Qc/0pGaJQmDxC\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 5 SYSTEMPATH\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(790): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Auth.php(42): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
CRITICAL - 2024-04-12 00:30:31 --> Error: Class "Firebase\JWT\JWT" not found
[Method: POST, Route: auth/register]
in APPPATH\Controllers\Auth.php on line 73.
 1 APPPATH\Controllers\Auth.php(46): App\Controllers\Auth->generateJWT('rafee1w4s33332@gmail.com')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
ERROR - 2024-04-12 00:31:01 --> mysqli_sql_exception: Duplicate entry 'rafee1w4s33332@gmail.com' for key 'email' in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(43): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}
CRITICAL - 2024-04-12 00:31:01 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'rafee1w4s33332@gmail.com' for key 'email'
[Method: POST, Route: auth/register]
in SYSTEMPATH\Database\BaseConnection.php on line 675.
 1 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 2 SYSTEMPATH\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(790): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Auth.php(43): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
CRITICAL - 2024-04-12 00:31:01 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'rafee1w4s33332@gmail.com' for key 'email'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`name`, `email`, `password`) VALUES (\'tauwsif3r3asfe3e1243\', \'rafee1w4s33332@gmail.com\', \'$2y$10$6MiuGykuBs/s.rLj.6ekwO/P1FZFzDFY4D1nqmJ8rEcJsI90LRjJm\')')
 2 SYSTEMPATH\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`name`, `email`, `password`) VALUES (\'tauwsif3r3asfe3e1243\', \'rafee1w4s33332@gmail.com\', \'$2y$10$6MiuGykuBs/s.rLj.6ekwO/P1FZFzDFY4D1nqmJ8rEcJsI90LRjJm\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 4 SYSTEMPATH\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(790): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Auth.php(43): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
CRITICAL - 2024-04-12 00:31:01 --> [Caused by] mysqli_sql_exception: Duplicate entry 'rafee1w4s33332@gmail.com' for key 'email'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `user` (`name`, `email`, `password`) VALUES (\'tauwsif3r3asfe3e1243\', \'rafee1w4s33332@gmail.com\', \'$2y$10$6MiuGykuBs/s.rLj.6ekwO/P1FZFzDFY4D1nqmJ8rEcJsI90LRjJm\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`name`, `email`, `password`) VALUES (\'tauwsif3r3asfe3e1243\', \'rafee1w4s33332@gmail.com\', \'$2y$10$6MiuGykuBs/s.rLj.6ekwO/P1FZFzDFY4D1nqmJ8rEcJsI90LRjJm\')')
 3 SYSTEMPATH\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`name`, `email`, `password`) VALUES (\'tauwsif3r3asfe3e1243\', \'rafee1w4s33332@gmail.com\', \'$2y$10$6MiuGykuBs/s.rLj.6ekwO/P1FZFzDFY4D1nqmJ8rEcJsI90LRjJm\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 5 SYSTEMPATH\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(790): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Auth.php(43): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
ERROR - 2024-04-12 00:33:08 --> mysqli_sql_exception: Duplicate entry 'rafee1@gmail.com' for key 'email' in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(43): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}
CRITICAL - 2024-04-12 00:33:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'rafee1@gmail.com' for key 'email'
[Method: POST, Route: auth/register]
in SYSTEMPATH\Database\BaseConnection.php on line 675.
 1 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 2 SYSTEMPATH\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(790): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\Auth.php(43): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
CRITICAL - 2024-04-12 00:33:08 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'rafee1@gmail.com' for key 'email'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 313.
 1 SYSTEMPATH\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`name`, `email`, `password`) VALUES (\'tauwsif3r3a\', \'rafee1@gmail.com\', \'$2y$10$QHb2K/1LG9p7ueekddrmWOsAVUkAIDiFad6LtwpnddOMM8b6xLeQa\')')
 2 SYSTEMPATH\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`name`, `email`, `password`) VALUES (\'tauwsif3r3a\', \'rafee1@gmail.com\', \'$2y$10$QHb2K/1LG9p7ueekddrmWOsAVUkAIDiFad6LtwpnddOMM8b6xLeQa\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 4 SYSTEMPATH\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(790): CodeIgniter\BaseModel->insert([...], true)
 7 APPPATH\Controllers\Auth.php(43): CodeIgniter\Model->insert([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
CRITICAL - 2024-04-12 00:33:08 --> [Caused by] mysqli_sql_exception: Duplicate entry 'rafee1@gmail.com' for key 'email'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 308.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `user` (`name`, `email`, `password`) VALUES (\'tauwsif3r3a\', \'rafee1@gmail.com\', \'$2y$10$QHb2K/1LG9p7ueekddrmWOsAVUkAIDiFad6LtwpnddOMM8b6xLeQa\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`name`, `email`, `password`) VALUES (\'tauwsif3r3a\', \'rafee1@gmail.com\', \'$2y$10$QHb2K/1LG9p7ueekddrmWOsAVUkAIDiFad6LtwpnddOMM8b6xLeQa\')')
 3 SYSTEMPATH\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`name`, `email`, `password`) VALUES (\'tauwsif3r3a\', \'rafee1@gmail.com\', \'$2y$10$QHb2K/1LG9p7ueekddrmWOsAVUkAIDiFad6LtwpnddOMM8b6xLeQa\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`name`, `email`, `password`) VALUES (:name:, :email:, :password:)', [...], false)
 5 SYSTEMPATH\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(790): CodeIgniter\BaseModel->insert([...], true)
 8 APPPATH\Controllers\Auth.php(43): CodeIgniter\Model->insert([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
ERROR - 2024-04-12 00:35:18 --> mysqli_sql_exception: Duplicate entry 'rafee1@gmail.com' for key 'email' in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(43): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}
ERROR - 2024-04-12 00:35:21 --> mysqli_sql_exception: Duplicate entry 'rafee1@gmail.com' for key 'email' in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(43): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}
CRITICAL - 2024-04-12 00:35:30 --> Error: Class "Firebase\JWT\JWT" not found
[Method: POST, Route: auth/register]
in APPPATH\Controllers\Auth.php on line 84.
 1 APPPATH\Controllers\Auth.php(46): App\Controllers\Auth->generateJWT('rafee12@gmail.com')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
ERROR - 2024-04-12 00:35:57 --> mysqli_sql_exception: Duplicate entry 'rafee12@gmail.com' for key 'email' in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(43): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}
ERROR - 2024-04-12 00:35:59 --> mysqli_sql_exception: Duplicate entry 'rafee12@gmail.com' for key 'email' in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(43): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}
ERROR - 2024-04-12 00:51:29 --> mysqli_sql_exception: Duplicate entry 'rafee12@gmail.com' for key 'email' in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(43): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}
ERROR - 2024-04-12 00:51:32 --> mysqli_sql_exception: Duplicate entry 'rafee12@gmail.com' for key 'email' in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(43): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}
CRITICAL - 2024-04-12 00:51:39 --> Error: Class "Firebase\JWT\JWT" not found
[Method: POST, Route: auth/register]
in APPPATH\Controllers\Auth.php on line 84.
 1 APPPATH\Controllers\Auth.php(46): App\Controllers\Auth->generateJWT('rafee122@gmail.com')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
ERROR - 2024-04-12 00:58:16 --> mysqli_sql_exception: Duplicate entry 'rafee122@gmail.com' for key 'email' in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(43): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}
ERROR - 2024-04-12 00:59:01 --> mysqli_sql_exception: Duplicate entry 'rafee122@gmail.com' for key 'email' in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(43): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}
ERROR - 2024-04-12 01:00:45 --> mysqli_sql_exception: Duplicate entry 'rafee122@gmail.com' for key 'email' in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(43): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}
CRITICAL - 2024-04-12 01:00:50 --> Error: Class "Firebase\JWT\JWT" not found
[Method: POST, Route: auth/register]
in APPPATH\Controllers\Auth.php on line 84.
 1 APPPATH\Controllers\Auth.php(46): App\Controllers\Auth->generateJWT('rafee1222@gmail.com')
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
ERROR - 2024-04-12 01:08:51 --> mysqli_sql_exception: Duplicate entry 'rafee1222@gmail.com' for key 'email' in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(43): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}
ERROR - 2024-04-12 01:09:08 --> mysqli_sql_exception: Duplicate entry 'rafee1222@gmail.com' for key 'email' in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(43): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}
ERROR - 2024-04-12 01:10:33 --> mysqli_sql_exception: Duplicate entry 'rafsee1222@gmail.com' for key 'email' in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(43): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}
ERROR - 2024-04-12 01:10:48 --> mysqli_sql_exception: Duplicate entry 'rafsee1222@gmail.com' for key 'email' in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(43): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}
ERROR - 2024-04-12 01:12:03 --> mysqli_sql_exception: Duplicate entry 'rafsee1222@gmail.com' for key 'email' in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(43): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}
ERROR - 2024-04-12 01:12:05 --> mysqli_sql_exception: Duplicate entry 'rafsee1222@gmail.com' for key 'email' in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(43): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}
ERROR - 2024-04-12 01:12:15 --> mysqli_sql_exception: Duplicate entry 'rafsee122w2@gmail.com' for key 'email' in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(43): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}
ERROR - 2024-04-12 01:16:43 --> mysqli_sql_exception: Duplicate entry 'rafsee122w2@gmail.com' for key 'email' in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(43): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}
CRITICAL - 2024-04-12 01:34:18 --> ArgumentCountError: Too few arguments to function App\Validation\UserRules::__construct(), 0 passed in C:\xampp1\htdocs\ci\system\Validation\Validation.php on line 724 and exactly 1 expected
[Method: CLI, Route: migrate:refresh]
in APPPATH\Validation\UserRules.php on line 12.
 1 SYSTEMPATH\Validation\Validation.php(724): App\Validation\UserRules->__construct()
 2 SYSTEMPATH\Validation\Validation.php(125): CodeIgniter\Validation\Validation->loadRuleSets()
 3 SYSTEMPATH\Config\Services.php(826): CodeIgniter\Validation\Validation->__construct(Object(Config\Validation), Object(CodeIgniter\View\View))
 4 SYSTEMPATH\Config\BaseService.php(320): CodeIgniter\Config\Services::validation(Object(Config\Validation), false)
 5 SYSTEMPATH\CLI\CLI.php(414): CodeIgniter\Config\BaseService::__callStatic('validation', [...])
 6 SYSTEMPATH\CLI\CLI.php(264): CodeIgniter\CLI\CLI::validate('temp', 'y', [...])
 7 SYSTEMPATH\Commands\Database\MigrateRefresh.php(78): CodeIgniter\CLI\CLI::prompt('Are you sure you want to refresh?', [...])
 8 SYSTEMPATH\CLI\Commands.php(70): CodeIgniter\Commands\Database\MigrateRefresh->run([...])
 9 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('migrate:refresh', [])
10 SYSTEMPATH\Boot.php(338): CodeIgniter\CLI\Console->run()
11 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
12 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
CRITICAL - 2024-04-12 01:35:41 --> ArgumentCountError: Too few arguments to function App\Validation\UserRules::__construct(), 0 passed in C:\xampp1\htdocs\ci\system\Validation\Validation.php on line 724 and exactly 1 expected
[Method: CLI, Route: migrate:refresh]
in APPPATH\Validation\UserRules.php on line 12.
 1 SYSTEMPATH\Validation\Validation.php(724): App\Validation\UserRules->__construct()
 2 SYSTEMPATH\Validation\Validation.php(125): CodeIgniter\Validation\Validation->loadRuleSets()
 3 SYSTEMPATH\Config\Services.php(826): CodeIgniter\Validation\Validation->__construct(Object(Config\Validation), Object(CodeIgniter\View\View))
 4 SYSTEMPATH\Config\BaseService.php(320): CodeIgniter\Config\Services::validation(Object(Config\Validation), false)
 5 SYSTEMPATH\CLI\CLI.php(414): CodeIgniter\Config\BaseService::__callStatic('validation', [...])
 6 SYSTEMPATH\CLI\CLI.php(264): CodeIgniter\CLI\CLI::validate('temp', 'y', [...])
 7 SYSTEMPATH\Commands\Database\MigrateRefresh.php(78): CodeIgniter\CLI\CLI::prompt('Are you sure you want to refresh?', [...])
 8 SYSTEMPATH\CLI\Commands.php(70): CodeIgniter\Commands\Database\MigrateRefresh->run([...])
 9 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('migrate:refresh', [])
10 SYSTEMPATH\Boot.php(338): CodeIgniter\CLI\Console->run()
11 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
12 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
CRITICAL - 2024-04-12 01:44:10 --> ArgumentCountError: Too few arguments to function App\Controllers\Auth::generateApiKey(), 0 passed in C:\xampp1\htdocs\ci\app\Controllers\Auth.php on line 37 and exactly 1 expected
[Method: POST, Route: auth/register]
in APPPATH\Controllers\Auth.php on line 66.
 1 APPPATH\Controllers\Auth.php(37): App\Controllers\Auth->generateApiKey()
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
CRITICAL - 2024-04-12 01:44:30 --> ArgumentCountError: Too few arguments to function App\Controllers\Auth::generateApiKey(), 0 passed in C:\xampp1\htdocs\ci\app\Controllers\Auth.php on line 37 and exactly 1 expected
[Method: POST, Route: auth/register]
in APPPATH\Controllers\Auth.php on line 66.
 1 APPPATH\Controllers\Auth.php(37): App\Controllers\Auth->generateApiKey()
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->register()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
ERROR - 2024-04-12 01:45:10 --> mysqli_sql_exception: Duplicate entry 'rafsee122w22@gmail.com' for key 'email' in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(43): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}
ERROR - 2024-04-12 01:46:25 --> mysqli_sql_exception: Duplicate entry 'rafsee122w22@gmail.com' for key 'email' in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(48): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}
ERROR - 2024-04-12 01:50:42 --> mysqli_sql_exception: Duplicate entry 'rafsee12w22@gmail.com' for key 'email' in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(48): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}
ERROR - 2024-04-12 02:00:10 --> mysqli_sql_exception: Duplicate entry 'rafsee12w22@gmail.com' for key 'email' in C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php:308
Stack trace:
#0 C:\xampp1\htdocs\ci\system\Database\MySQLi\Connection.php(308): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(721): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp1\htdocs\ci\system\Database\BaseConnection.php(635): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp1\htdocs\ci\system\Database\BaseBuilder.php(2325): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp1\htdocs\ci\system\Model.php(382): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp1\htdocs\ci\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp1\htdocs\ci\system\Model.php(790): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp1\htdocs\ci\app\Controllers\Auth.php(48): CodeIgniter\Model->insert(Array)
#8 C:\xampp1\htdocs\ci\system\CodeIgniter.php(933): App\Controllers\Auth->register()
#9 C:\xampp1\htdocs\ci\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#10 C:\xampp1\htdocs\ci\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp1\htdocs\ci\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#12 C:\xampp1\htdocs\ci\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp1\htdocs\ci\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 C:\xampp1\htdocs\ci\system\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdoc...')
#15 {main}
CRITICAL - 2024-04-12 02:00:56 --> Error: Call to undefined function App\Controllers\email_verify()
[Method: POST, Route: auth/login]
in APPPATH\Controllers\Auth.php on line 145.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->login()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 7 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
CRITICAL - 2024-04-12 02:00:59 --> Error: Call to undefined function App\Controllers\email_verify()
[Method: POST, Route: auth/login]
in APPPATH\Controllers\Auth.php on line 145.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Auth->login()
 2 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 7 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('C:\\xampp1\\htdocs\\ci\\public\\index.php')
ERROR - 2024-04-12 02:02:39 --> Exception occurred during user login: Undefined array key "email_verified"
ERROR - 2024-04-12 02:06:28 --> Exception occurred during user login: Undefined array key "email_verified"
ERROR - 2024-04-12 02:06:38 --> Exception occurred during user login: Undefined array key "email_verified"
ERROR - 2024-04-12 02:07:05 --> Exception occurred during user login: Undefined array key "email_verified"
ERROR - 2024-04-12 02:07:28 --> Exception occurred during user login: Undefined array key "email_verified"
ERROR - 2024-04-12 02:10:24 --> Exception occurred during user login: Undefined array key "email_verified"
